/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Self Claimed Business Profile
 */
export interface BusinessProfile {
  id: string;
  bio?: string;
  skills?: string[];
  roles?: string[];
  services?: string[];
  languages?: string[];
  desiredHourlyFee?: number;
  desiredWorkStyle?: string;
  paymentMethods?: string[];
  coverImage?: string;
  workStatus?: string;
  tags?: string[];
  baseLocation?: string;
  createdAt?: string;
  updatedAt?: string;
  [k: string]: unknown;
}
