/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Event {
  name: string;
  icon?: string;
  desc?: string;
  url?: string;
  organizationId?: string;
  tags?: string[];
  startDate?: string;
  endDate?: string;
  [k: string]: unknown;
}
