/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Tx {
  /**
   * hash of the transaction
   */
  hash: string;
  /**
   * payee address
   */
  to?: string;
  /**
   * payer address
   */
  from?: string;
  /**
   * whether or not DID is payer
   */
  isPayer?: boolean;
  /**
   * paid value
   */
  value?: string;
  /**
   * paid token symbol
   */
  tokenSymbol?: string;
  /**
   * paid token decimal
   */
  tokenDecimal?: number;
  /**
   * fiat price at the time of the transaction
   */
  fiatValue?: string;
  /**
   * currently only support USD
   */
  fiatSymbol?: string;
  /**
   * network id of the transaction
   */
  networkId?: number;
  /**
   * Time stamp of transaction occurrence
   */
  issuedTimestamp?: string;
  relatedAddresses?: string[];
  relatedTxHashes?: string[];
  [k: string]: unknown;
}
