/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import {
  DeliverableItem,
  Signatures,
  Transaction,
} from './VerifiableWorkCredential.js';

export type CreatedAt = string;

export interface WorkCredential {
  id: string;
  subject: WorkSubject;
  signature?: Signatures;
  createdAt?: CreatedAt;
  updatedAt?: string;
}
export interface WorkSubject {
  work?: Work;
  tx?: Transaction;
  deliverables?: DeliverableItem[];
  client?: Client;
  [k: string]: unknown;
}
export interface Work {
  id: string;
  /**
   * paid value
   */
  value?: string;
  /**
   * paid value
   */
  tax?: string;
  /**
   * work summary
   */
  summary: string;
  /**
   * work detail
   */
  detail?: string;
  /**
   * work genre e.g, Dev, Design etc
   */
  genre?: string;
  tags?: string[];
  /**
   * currently support fulltime, parttime, and onetime
   */
  jobType?: string;
  /**
   * Time stamp of work started
   */
  startTimestamp?: string;
  /**
   * Time stamp of work ended
   */
  endTimestamp?: string;
  /**
   * a transaction platform if exists e.g, gitcoin
   */
  platform?: string;
  /**
   * hash value of all work descriptions(summary, detail, deliverables)
   */
  deliverableHash?: string;
  /**
   * CRDL issue date
   */
  issuedAt: string;
  /**
   * organization Id if exist
   */
  organization?: string;
  [k: string]: unknown;
}

export interface Client {
  /**
   * name or DID
   */
  format?: string;
  /**
   * Client Info
   */
  value?: string;
  [k: string]: unknown;
}
